name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14' # Thay đổi phiên bản Node.js nếu cần

    - name: Install dependencies
      run: npm install # Hoặc yarn install nếu bạn sử dụng Yarn

    - name: Run tests
      run: npm test # Hoặc lệnh kiểm tra của bạn