name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14' # Thay đổi phiên bản Node.js nếu cần

    - name: Install dependencies
      run: npm install # Hoặc yarn install nếu bạn sử dụng Yarn

    - name: Build project
      run: npm run build # Hoặc lệnh xây dựng của bạn

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist # Thay đổi đường dẫn nếu cần